# Generated by Django 3.0.5 on 2021-04-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image_link',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='specifications',
            new_name='specs',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='stock_count',
            new_name='stock',
        ),
        migrations.AddField(
            model_name='item',
            name='campaign',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
